apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  ports:
    - name: ui-service-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ui-service