apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: nidhisankhe1/quantaas-backend-service:gke
          ports:
            - containerPort: 5002
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: minio-configmap
            - secretRef:
                name: minio-secret
            - secretRef:
                name: mongodb-secret
            - secretRef:
                name: kafka-secret
          
