apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - name: backend-service-port
      protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    app: backend-service