apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-service
  template:
    metadata:
      labels:
        app: trainer-service
    spec:
      containers:
        - name: trainer-service
          image: dishagundecha99/quantaas-trainer-service:latest
          ports:
            - containerPort: 5002
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: trainer-service-configmap 
            - secretRef:
                name: minio-secret
            - secretRef:
                name: mongodb-secret
            - secretRef:
                name: kafka-secret
          
